---
- name: Ensure backup directory exists
  ansible.builtin.file:
    path: "{{ backup_directory }}"
    mode: 0644
    state: directory

- name: Install pre-requisite tools
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
  - tar
  - gzip

- name: Install backup script
  ansible.builtin.template:
    src: backup_directory.sh.j2
    dest: "{{ parent_directory }}/backup_directory_{{ directory }}.sh"
    mode: 0644

- name: Run script daily
  ansible.builtin.cron:
    name: "Backup directory - {{ source_directory }}"
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "3"
    job: "{{ parent_directory }}/backup_directory_{{ directory }}.sh"
    state: present
